### ISSUE TITLE
Missing Lead functions

### ISSUE THREAD

**Issue by GuerrillaCoder** [DavidRouyer/pipedrive-dotnet#99] opened 2021-12-02 19:43 UTC
I just added in the missing Lead create function in my fork and there are some weird issues.  The PD lead endpoint follows the same format as the deal endpoint but there are some differences.

Deal endpoint allows null properties, leads does not.
Deal endpoint accepts visibility as an integar, leads accepts it as a string
Deal endpoint receives value as a double, leads receives it as an object

This means if you use the same pattern as every other endpoint then it doesn't actually work because it needs to be serialized differently.

I am going to do a quick hack to make it work in my code but posting this to save anyone else time who decides to try to add those endpoints

**Comment by DavidRouyer** [comment] 2022-10-11 21:36
Duplicate of https://github.com/DavidRouyer/pipedrive-dotnet/issues/56

**Closed by DavidRouyer** 2022-10-11 21:36 UTC
