### ISSUE TITLE
Cannot update a person with customFields

### ISSUE THREAD

**Issue by adrianNegrusa** [DavidRouyer/pipedrive-dotnet#26] opened 2019-10-03 06:48 UTC
Hi David,
I need a way to update a person address, based on zip/code or postal_address!!!
I've made my own method(PUT-REST and JSON) in order to update fields for a person.
Here is my small example:

            PersonUpdate personUpdate = new PersonUpdate();
            List<Phone> lPhones = new List<Phone>();                 
            
            //customFields.Add("phone", new StringCustomField(phone));      
            //customFields.Add("postal_address", new AddressCustomField(postalcode));
            try
            {
                //Person pExUpdate = await PipedrivePerson.Person.Get(id);
                
                Dictionary<string, string> customFields = new Dictionary<string, string>();
                customFields.Add("postal_address", address1+","+city+","+country);
                customFields.Add("postal_address_postal", postalcode);
                customFields.Add("phone", phone);
                customFields.Add("email", email);
                customFields.Add("postal_address_route", address1);
                customFields.Add("postal_address_country", country);
                customFields.Add("postal_address_locality", city);

                //pExUpdate.CustomFields = customFields;               
                //lPhones.Add(new Phone() { Label = "", Primary = true, Value = phone });
                //pExUpdate.Phone = lPhones;

                var personFields = JsonConvert.SerializeObject(customFields);
                MakePutAction(personFields, urlupdateField);
                //Person pUpdate=await PipedrivePerson.Person.Edit(id, personUpdate);
                //pExUpdate.ToUpdate();

**Comment by DavidRouyer** [comment] 2019-10-22 15:22
Duplicate of #27

**Closed by DavidRouyer** 2019-10-22 15:22 UTC
